TLS configure for OIDC connector
dexidp/dex pull request #1632
Opened 2020-01-20 17:09 UTC by xtremerui

This PR adds two configurable fiels `RootCAs` and `InsecureSkipVerify` to OIDC connector. When openning a connection to OIDC connect provider, it will use a httpclient based on these two fields.

2020-11-05 04:34 UTC, xtremerui commented
@sagikazarmark just a quick raincheck here to see if this PR falls in the path. I am seeing some connectors providing TLS config (more or less). For example,

Github:
https://github.com/dexidp/dex/blob/6cdbb594064740794a79f30da83be92ec06c22e8/connector/github/github.go#L99-L108

LDAP:
https://github.com/dexidp/dex/blob/6cdbb594064740794a79f30da83be92ec06c22e8/connector/ldap/ldap.go#L255-L269

openshift:
https://github.com/dexidp/dex/blob/6cdbb594064740794a79f30da83be92ec06c22e8/connector/openshift/openshift.go#L81-L84

Thank you for your time!

2021-11-10 18:29 UTC, xtremerui commented
Hi could I get some feedbacks on thie PR? Thx @sagikazarmark

2022-10-03 16:38 UTC, sagikazarmark requested changes
Apologies for the delay on this one.

I had a couple notes, but looks OK overall.

2022-10-08 01:36 UTC, xtremerui commented on connector/oidc/oidc.go
> +func newHTTPClient(rootCAs []string, insecureSkipVerify bool) (*http.Client, error) {
I have extract the func out to a package named `httpclient`. The test of it requires some test certs as you can see. The instruction for regenerate the test certs are in the readme. Test certs are set to expired in 10 years.

Please let me know if you want set up the test differently. Thank you!

2022-11-04 12:48 UTC, nabokihms commented
@xtremerui Thanks for your work, and sorry for this PR being delayed for so long. My apologies.

I am ready to merge this. Could you please fix the conflicts?

2022-11-05 01:33 UTC, xtremerui commented
@nabokihms thx its done.

2022-11-07 09:28 UTC, nabokihms approved these changes
LGTM

2022-11-07 09:29 UTC, merged