Feature: groups in Gitea
dexidp/dex pull request #1789
Opened 2020-08-31 22:32 UTC by techknowlogick

2020-10-06 07:14 UTC, techknowlogick commented
gentle ping for reviews.

2021-01-18 19:38 UTC, techknowlogick commented
Conflicts have been resolved.

2021-01-18 19:41 UTC, sagikazarmark commented
Thanks @techknowlogick !

I added reviewing it to my backlog: https://github.com/users/sagikazarmark/projects/1#card-53059357

2021-03-23 00:59 UTC, techknowlogick commented
I've just resolved the conflicts.

2021-06-12 01:57 UTC, techknowlogick commented
@sagikazarmark 👋 Hey, is there anything I can do to help get this merged?

2021-10-14 04:15 UTC, techknowlogick commented
@nabokihms @sagikazarmark 👋 Hi, hope all is well. Is there anything I can do to help get this PR merged? Could I volunteer as a maintainer to take some load off your shoulders?

2021-11-11 21:50 UTC, nabokihms requested changes
Overall it looks good. Could you please write a test for the new feature? In addition, pay attention to group filters (maybe there is a way to reuse code).

2021-11-11 21:50 UTC, nabokihms commented on connector/gitea/gitea.go
> +// groupsRequired returns whether dex requires GitHub's 'read:org' scope. Dex
I think the comment was just copied.
```suggestion
// groupsRequired returns whether dex requires Gitea 'read:org' scope. Dex
```

2021-11-11 21:50 UTC, nabokihms commented on connector/gitea/gitea.go
> +// groupsRequired returns whether dex requires GitHub's 'read:org' scope. Dex
And what about the other part of the comment? Especially the part about `org`. Is it correct?

2021-11-11 21:50 UTC, nabokihms commented on connector/gitea/gitea.go
> +	keys := make(map[string]bool)
NIT: We usually use map[string]struct{}

2022-01-15 01:51 UTC, techknowlogick commented
Thanks @nabokihms I've just updated the code comment, and coding style to align with existing dex code

2022-01-19 23:29 UTC, techknowlogick commented
I'm not sure these CI fails are related, looking at them it is something to do with storage which this PR doesn't touch.

2022-01-20 09:08 UTC, sagikazarmark commented
@techknowlogick 

```
Error: connector/gitea/gitea.go:355:17: undefined: ioutil
# github.com/dexidp/dex/connector/gitea [github.com/dexidp/dex/connector/gitea.test]
Error: connector/gitea/gitea.go:355:17: undefined: ioutil
FAIL	github.com/dexidp/dex/cmd/dex [build failed]
```

2022-04-08 04:43 UTC, techknowlogick commented
@sagikazarmark ah thanks for catching that. I've resolved it, along with now passing the linter.

2022-04-15 07:01 UTC, nabokihms approved these changes
I am ok with this being merged.
1. There are some NITs left. Could you please look through them and apply suggestions?
2. We refactored out Docker build a little. Could you please rebase this PR on master in order to run the docker build job successfully?

2022-04-15 12:30 UTC, nabokihms commented
@techknowlogick only DCO thing left.

2022-04-20 01:38 UTC, techknowlogick commented
@nabokihms there we go, all passing. thanks for your help on this :)

2022-04-20 06:30 UTC, merged

2022-04-20 06:30 UTC, nabokihms commented
@techknowlogick looks good to me. Thank you for your contribution!