fix: use /token endpoint to get tokens with device flow
dexidp/dex pull request #2010
Opened 2021-02-20 10:02 UTC by nabokihms

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>

#### Overview
[rfc6749#section-3.2](https://tools.ietf.org/html/rfc6749#section-3.2)
* Make `/token` endpoint responding to requests with device auth grant
* Allow only POST requests `/token` endpoint
* Do not search for a client in storage if an invalid grant type is provided

#### What this PR does / why we need it

Fixes https://github.com/dexidp/dex/issues/1953 
As was mentioned in the issue above, the main problem that the token endpoint is not discoverable.

#### Special notes for your reviewer
This MR leaves the possibility to get a token from the `/device/token` endpoint. 

#### Does this PR introduce a user-facing change?

There are no breaking changes, but it will be better to avoid using /device/token endpoint in the feature.

```release-note
Make /token endpoint responding to requests with device auth grant.
```

2021-02-20 12:13 UTC, sagikazarmark commented
Should we deprecate the `/device/token` endpoint?

2021-02-20 12:24 UTC, nabokihms commented
Yes, I think so. I left a to-do but did nothing with deprecation. Maybe adding some sort of warning on endpoint call will be good enough.
"Some of Dex clients called the deprecated /device/token endpoint. It will be removed in a future release."

Something like this.

2021-02-20 12:27 UTC, sagikazarmark commented
For me, deprecation would mean

- a comment in the code somewhere
- potentially a warning log message
- a note in the release notes

2021-02-24 21:31 UTC, sagikazarmark requested changes

2021-02-24 21:31 UTC, sagikazarmark commented on server/deviceflowhandlers.go
> +	s.logger.Warn(`The "/device/token" endpoint will be removed in a future release.`)
Can we make this a single log line? And maybe make the message a bit more concise?

2021-02-24 21:31 UTC, sagikazarmark commented on server/server_test.go
> +			tokenURL.Path = path.Join(tokenURL.Path, "/token")
Can we add a test with the old path to make sure it's still functional?

2021-02-24 21:31 UTC, sagikazarmark commented on server/deviceflowhandlers.go
> +func (s *Server) handleDeviceTokenGrant(w http.ResponseWriter, r *http.Request) {
I think this name is a bit confusing and ambiguous with the `handleDeviceToken` name. Maybe call it something like `deprecatedDeviceTokenHandler` or `handleDeviceTokenDeprecated`.

2021-03-25 14:50 UTC, sagikazarmark approved these changes
LGTM, thanks

2021-04-29 21:43 UTC, justenwalker commented
@sagikazarmark Anything preventing this from being merged/closed?

2021-05-01 11:24 UTC, merged