Allow a user to overwrite Auth and Token URL
dexidp/dex pull request #2147
Opened 2021-05-28 18:03 UTC by rikatz

Signed-off-by: Ricardo Katz <rkatz@vmware.com>

#### Overview

This change adds two new configuration fields in OIDC Connector: authURL and tokenURL.

#### What this PR does / why we need it

This change adds two new configuration fields in OIDC Connector: authURL and tokenURL.

Dex uses the go-oidc library, which does auto-discovery based in .well-known/openid-configuration from the issuer configured.

Happens that in some cases the issuer is not the same as Auth and Token URL. In this case, is desired that the user can overwrite those configurations (instead of relying into the auto discovered by go-oidc) allowing the correct login page redirection.

#### Special notes for your reviewer

In some cases UserInfoURL and JWKSURL should also be overwritable. The main issue is that, opposite to Auth and Token URL, go-oidc does not support overwriting UserInfo and JWKS but this might appear as a need in future

#### Does this PR introduce a user-facing change?

```release-note
Add authURL and tokenURL configurations in OIDC connector
```

2021-06-15 22:19 UTC, scottcrawford03 commented
+1 to this change

2021-09-16 18:37 UTC, nabokihms commented
@rikatz sorry, I missed this PR.

The subject makes sense. For example, the oauth2 proxy allows you to override detected URLs or even make requests without detection. Even Google [has its hacks](https://github.com/coreos/go-oidc/blob/15b94d97d90c9455981dbdd90a021d34254cfdaf/oidc/verify.go#L238) inside of the go-oidc library. I believe that we can merge this PR if you are still willing to work on it.

Could you tell us a little more about your use case?

Are the discovery endpoint and the token endpoint served by the same IDP but in different domains, or maybe you want to send a code to get the token to a different service?

2021-09-16 20:03 UTC, rikatz commented
Hi @nabokihms and thanks for the response :)

So yes, this is exactly the case. The Discovery endpoint is served from a different domain from the auth and token endpoint. I know, for example Keycloak also supports overwriting this.

I was doing some researches about that, and actually this is allowed (when dealing with "multi host" discovery endpoints).

I will rebase here to remove the go.sum conflicts, but feel free to reach me about any other question.

Thank you very much!

2021-09-16 20:11 UTC, rikatz commented
done :)

2021-10-04 14:57 UTC, nabokihms requested changes
There is a couple of thoughts about this PR. As for me, everything looks good.

2021-10-04 14:57 UTC, nabokihms commented on connector/oidc/oidc.go
> +	// TokenURL provides a way to user overwrite the Token URL from .well-known/openid-configuration
Could you also add these options to the [documentation](https://github.com/dexidp/website/blob/main/content/docs/connectors/oidc.md)?

2023-08-28 07:40 UTC, m44soroush commented
hey guys, any updates on this issue?
we need this feature to overwrite auth and token URL.
It seems this change haven't merged to the main branch.

2024-01-10 19:03 UTC, closed without merging