OIDC connector: Support cases where there is no id_token when using a refresh_token grant
dexidp/dex pull request #2505
Opened 2022-05-06 04:02 UTC by Blorpy

Signed-off-by: Anthony Brandelli <abrandel@cisco.com>

#### Overview

Allows for dex to function with IDPs that do not return an ID token in the reply when using a refresh_token grant. 

#### What this PR does / why we need it

Although this seems to be rare, the OIDC spec does not require that an id_token be present in the reply when using a refresh_token grant. Additional info in #2498. 

This is a toggle in PingFed, so there is at least one common IDP out there where there won't always be a refresh token. 

Closes #2498 

#### Special notes for your reviewer

Note that if a user has an IDP where ID tokens aren't present when using a refresh_token grant, AND also chooses not to enable the userinfo endpoint, this will choke. The claims have to come from somewhere, so I would say this really is just an unsupported configuration should someone choose to try this. The OIDC spec says that userinfo must always contain the sub additionally. 

I tried to keep behaviour as close as possible to current. Although its extra code, and probably not needed, I chose to prefer the sub from the ID token if its present, over assigning the one from the userinfo. 

#### Does this PR introduce a user-facing change?

```release-note

NONE

```

2022-05-18 11:12 UTC, nabokihms requested changes
Thank you, @Blorpy. Overall, everything looks good. I left a couple of suggestions to you, and adding tests is also required for these changes.

2022-05-18 11:12 UTC, nabokihms commented on connector/oidc/oidc.go
> +	createCaller = "create"
NIT: It looks better for me to use more strict internal constant markers.

```go
type caller uint

const (
    createCaller caller = iota
    refreshCaller
)
```

2022-05-19 16:23 UTC, Blorpy commented
Thanks for the excellent feedback! I have implemented the requested changes, but will leave this in draft until I have the tests written.

2022-05-20 03:38 UTC, Blorpy commented
I was surprised to see there were no refresh tests already for this connector, so I had to do a bit of plumbing here. I chose to break out my tests to a new function, primarily because the existing function was for the initial identity creation, and I didn't want to mess with it too much. 

I have to deal with test cases where there will be no ID tokens, and because the functions call setupServer once which will dictate the ID token behaviour for the lifetime of that test case, I figured it was just easier to write another small test function.

2022-05-20 04:04 UTC, Blorpy commented
Sorry for the messed up push here, will fix

2022-05-20 04:05 UTC, closed without merging