fix: Fallback when group claim is a string instead of an array of strings
dexidp/dex pull request #2639
Opened 2022-08-24 13:54 UTC by JoooostB

#### Overview
When using the OIDC provider, in combination with Microsoft ADFS using OpenID, groups can be filtered on Microsoft's side. Whenever the result of this filtering consists of only one group, the response back to Dex will be a string instead of an array of strings.

**OIDC response examples:**
_Response with multiple groups:_
```json
{
  "aud": "microsoft:identityserver:XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX",
  "iss": "http://domain.acme.com/adfs/services/trust",
  "iat": 1661346019,
  "exp": 1661349619,
  "email": "myemailaddress@acme.com",
  "given_name": "Henk",
  "family_name": "Vries, De",
  "unique_name": "Vries, Henk de",
  "winaccountname": "henkie",
  "groupsid": [
    "K8s_P_Group1",
    "K8s_P_Group2"
  ],
  "group": [
    "K8s_P_Group1",
    "K8s_P_Group2"
  ],
  "apptype": "Confidential",
  "appid": "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "auth_time": "2022-08-24T12:17:06.060Z",
  "ver": "1.0",
  "scp": "openid"
}
```

 _Response with one group:_
```json
{
  "aud": "microsoft:identityserver:XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX",
  "iss": "http://domain.acme.com/adfs/services/trust",
  "iat": 1661346019,
  "exp": 1661349619,
  "email": "myemailaddress@acme.com",
  "given_name": "Henk",
  "family_name": "Vries, De",
  "unique_name": "Vries, Henk de",
  "winaccountname": "henkie",
  "groupsid": "K8s_P_Group1",
  "group": "K8s_P_Group1",
  "apptype": "Confidential",
  "appid": "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "auth_time": "2022-08-24T12:17:06.060Z",
  "ver": "1.0",
  "scp": "openid"
}
```
#### What this PR does / why we need it
This PR adds a fallback to the OIDC connector to add support for a singular group received as a string instead of an array of strings.

```release-note
NONE
```

Co-authored-by: Michiel van Pouderoijen <michiel@pouderoijen.nl>
Signed-off-by: Joost Buskermolen <joost@buskervezel.nl>

2022-08-24 13:59 UTC, nabokihms requested changes
@JoooostB great job! Seems ok to me, but adding a test is required to consolidate the logic.

2022-08-24 14:08 UTC, nabokihms commented
Related https://github.com/dexidp/dex/pull/2562

2022-08-24 14:37 UTC, JoooostB commented
@nabokihms I moved the fallback outside of the if statement for custom `groupsKey` to make sure it's executed when the default `groupsKey` is used. As requested I also created a testcase containing a singular group as a string.

2022-08-25 08:55 UTC, nabokihms approved these changes

2022-08-25 08:55 UTC, merged