Reduce HTTP client creations in Keystone connector
dexidp/dex pull request #2659
Opened 2022-09-12 22:29 UTC by erwinvaneyk

#### Overview

Refactors the Keystone connector to reduce the number of instantiations of HTTP clients.

#### What this PR does / why we need it

Improves performance and reduces boilerplate.

#### Special notes for your reviewer

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2022-09-13 07:42 UTC, nabokihms commented
@erwinvaneyk I like the idea! Could you also fix the tests so that we can merge this PR?

2022-09-14 20:59 UTC, erwinvaneyk commented
Hi @nabokihms thanks for the quick review, will look into the CI failures. They were running fine locally.

2022-09-20 05:19 UTC, nabokihms commented on connector/keystone/keystone.go
> +		client:        http.DefaultClient,
The test's problem is that they didn't use the `Open` method and manually create connector instances. You should add `http.DefaultClient` to every `conn{}` in tests.

2022-09-20 05:19 UTC, nabokihms requested changes
Waiting for tests to be fixed.

2022-09-22 23:23 UTC, erwinvaneyk commented
@nabokihms fixed the tests. Thanks for the pointer, my local setup was skipping some of them apparently.

2022-09-23 21:01 UTC, nabokihms approved these changes

2022-09-23 21:02 UTC, merged

2022-09-23 21:02 UTC, nabokihms commented
@erwinvaneyk, many thanks. Great work.