Add support for extra claims to authproxy connector
dexidp/dex pull request #2851
Opened 2023-03-08 16:02 UTC by mkjpryor

#### Overview

This PR adds support for some additional headers to be propagated into claims in the authproxy connector.

#### What this PR does / why we need it

I am using Dex with authproxy to turn an existing IdP, whose code is not under my control, into an OIDC provider. I want to be able to propagate the user ID and email address from the underlying IdP as OIDC claims alongside the username, which is not possible with the current headers and claims supported by the authproxy connector.

This PR adds support for two extra headers that can be used to propagate the user ID and email from the underlying IdP, and sets the claims. When these additional headers are not set, it reduces to the previous mode.

#### Special notes for your reviewer

#### Does this PR introduce a user-facing change?

```release-note
Adds support for two additional headers, for user ID and email, to the authproxy connector.
```

2023-06-21 14:58 UTC, nabokihms requested changes
The feature looks good to me.
1. The test is required.
2. Linter has its suggestions that should be satisfied 🙂

2023-11-13 16:25 UTC, mkjpryor commented
@nabokihms 

I have rebased, addressed the linting issues and added an extra test. Can you re-review please?

2023-12-28 10:16 UTC, nabokihms approved these changes

2023-12-28 10:17 UTC, merged

2023-12-28 10:17 UTC, nabokihms commented
@mkjpryor sorry for the long delay. Merged!