fix: Fail if OIDC config contains hosted domains
dexidp/dex pull request #2937
Opened 2023-05-10 21:51 UTC by nabokihms

#### Overview

Fail if the hostedDomains option is specified in an OIDC connector config

#### What this PR does / why we need it

The option was removed. After the upgrade, users still using OIDC connectors for their Google providers may accidentally open access to more people than before.

#### Special notes for your reviewer

2023-05-12 20:03 UTC, sagikazarmark requested changes
Retargeted to 2.37.0

2023-05-12 20:03 UTC, sagikazarmark commented on connector/oidc/oidc.go
> +	// Deprecated: will be removed in feature releases.
Nit: s/feature releases/a future release/ ?

2023-05-12 20:03 UTC, sagikazarmark commented on connector/oidc/oidc.go
> +		return nil, fmt.Errorf("hostedDomains option does not work anymore, consider switching to the Google connector")
```suggestion
		return nil, fmt.Errorf("Hosted domains option had been deprecated and removed. Consider switching to the Google connector")
```

2023-05-16 21:04 UTC, dlipovetsky commented on connector/oidc/oidc.go
> +	// Now this option does nothing. To work with Google, users should migrate to using the Google connector.
```suggestion
	// HostedDomains was an optional list of whitelisted domains when using the OIDC connector with Google. Only users from a whitelisted domain were allowed to log in.
	// Support for this option was removed from the OIDC connector in f07a58a7f1514eaf6e634bb773584cefe98e84ed.
	// The Google connector supports this option.
```

2023-05-16 21:06 UTC, dlipovetsky commented on connector/oidc/oidc.go
> +		return nil, fmt.Errorf("hostedDomains option does not work anymore, consider switching to the Google connector")
```suggestion
		return nil, fmt.Errorf("Support for the HostedDomains option was removed from the OIDC connector. Consider using the Google connector, which supports this option.")
```

2023-05-16 23:40 UTC, nabokihms commented
Because of the overlapping review comments, I took parts from both suggestions. Thanks @dlipovetsky @sagikazarmark

2023-05-23 15:34 UTC, merged