GitLab connector: add GitLab additional group with role
dexidp/dex pull request #2941
Opened 2023-05-11 12:19 UTC by zvlb

#### Overview

Issue - https://github.com/dexidp/dex/issues/2763
In this PR I add logic to add information about group Permission for user to GitLab connector.

### Before MR:
Login with Gitlab Connector
```
time="2023-05-11T12:01:02Z" level=info msg="login successful: connector "gitlab", username="Vladimir Zemtsov", preferred_username="zvlb", email="***", groups=["group1", "group1/group1.1", "group1/group1.2", "group2", "group3"]
```

### After MR:
```
time="2023-05-11T12:05:22Z" level=info msg="login successful: connector "gitlab", username="Vladimir Zemtsov", preferred_username="zvlb", email="***", groups=["group1", "group1/group1.1", "group1/group1.2", "group2", "group3", "group1:owner", "group1/group1.1:owner", "group1/group1.2:owner", "group2:maintainer"]
```
If zvlb user have Owner-access to group `group1` and Maintainer-access to group `group2`. (And have Reporter or Guest access to group3)

In GitLab If you have access to some group, you have same access to nested groups (ot Projects), but API request [/oauth/userinfo](https://docs.gitlab.com/ee/api/oauth2.html) return information only about "main" groups. I add logic to add permition-postfix for nested groups. 

#### What this PR does / why we need it

In my case I want use dex for autentification and use group-permission information for control users-access in my application.

#### Does this PR introduce a user-facing change?

If this PR will be applyed I add information [to docs](https://github.com/dexidp/website/blob/main/content/docs/connectors/gitlab.md) 

```release-note
GitLab connector: add GitLab additional group with role
```

2023-05-11 19:58 UTC, sagikazarmark commented
Hey @zvlb !

Thanks for the contribution!

I wonder if we should make this feature more generic. For example: allow users to format group names somehow:

- %name%
- %name%:%role%
- %name%;%role%
- %name_full_path%

We can make that an incremental change probably.

2023-05-11 19:58 UTC, sagikazarmark commented
@nabokihms what do you think?

2023-05-12 04:57 UTC, zvlb commented
> I wonder if we should make this feature more generic. For example: allow users to format group names somehow:
> 
> * %name%
> * %name%:%role%
> * %name%;%role%
> * %name_full_path%

I think is not a good idea. `%name%` - it's GitLab group name? But if GitLab we can have groups with the same name, but different paths. For example:
- /group1/test-group
- /group2/test-group
In this case, we have 2 groups with the name `test-group`, but it's different groups with different permission

2023-05-21 18:34 UTC, nabokihms requested changes
@zvlb Márk's idea is to make the feature more generic because the approach to add boolean flags for all new features scales poorly. By looking at [Gitlab's doc](https://docs.gitlab.com/ee/integration/openid_connect_provider.html#shared-information), I can imagine at least one more boolean flag - return only groups with direct membership.

The best option is to add a way to customize how user attributes are extracted from the token, e.g., add some extended claim mappings that allow mapping Gitlab token claims to Dex token claims. 

Example of what it can look like using CEL:
```yaml
groups: |
  claims.groups 
  + claims.groups."https://gitlab.org/claims/groups/owner".map(s, s +":owner")
  + claims.groups."https://gitlab.org/claims/groups/maintainer".map(s, s +":maintainer")
  + claims.groups."https://gitlab.org/claims/groups/developer".map(s, s +":developer")
```

With its current implementation, the feature looks too specific to me. Other connectors, like OIDC, can also benefit from extended claim mappings.

2023-06-01 14:27 UTC, zvlb commented on connector/gitlab/gitlab.go
> +
Added

2023-06-01 14:30 UTC, zvlb commented
I need some time to create unit tests

2023-07-13 09:12 UTC, zvlb commented
Someone?

2023-07-18 08:49 UTC, progmatv commented
Hello guys! We really need this PR to approve =)

2023-08-03 12:46 UTC, svbrsn commented
can you merge this PR? really helpful

2023-08-08 05:50 UTC, zvlb commented
Anyone?
@nabokihms 
@sagikazarmark

2023-12-15 18:46 UTC, eduherraiz commented
@zvlb thank you for the work!
This looks very promising for me to manage argo roles based on gitlab's groups permissions.
Is there any way to merge this and do some other future efforts to be more generic for use in other connectors?
cc @nabokihms @sagikazarmark

2024-04-10 15:20 UTC, zvlb commented
someone?

2024-07-18 12:47 UTC, zvlb commented
????

2024-10-24 20:17 UTC, nabokihms approved these changes
Thank you for your patience. I'm ready to merge this. LGTM!

P.S. could you please add the new option here https://dexidp.io/docs/connectors/gitlab/?

2024-10-24 20:18 UTC, merged

2024-10-24 20:18 UTC, nabokihms commented
We will think about generic mutations of the token claim for connectors in the future.

2024-10-24 20:24 UTC, zvlb commented
@nabokihms 

Hello. Thank you for your work! I will update the documentation tomorrow.

I also have one more change in the connector that I’m using in my production environment. With this change, besides GitLab groups, it also collects projects where the user is a member. I will also submit a merge request with this functionality tomorrow. (However, this will require discussion, since to get the user’s projects, the GitLab application will need broader permissions (access to the API). This might be a controversial decision.
(Currently, for Dex to work, only access to GitLab userinfo is required.)