verify access tokens by checking getuserinfo during a token exchange
dexidp/dex pull request #3031
Opened 2023-07-04 19:11 UTC by seankhliao

#### Overview

Followup on #2806 for better access token handling.
verify access tokens by checking getuserinfo during a token exchange

#### What this PR does / why we need it

The provider.Verifier.Verify endpoint we were using only works with ID tokens. This isn't an issue with systems which use ID tokens as access tokens (e.g. dex), but for systems with opaque access tokens (e.g. Google / GCP), those access tokens could not be verified. Instead, check the access token against the getUserInfo endpoint.

#### Special notes for your reviewer

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2023-07-06 18:07 UTC, nabokihms requested changes
There is a question to discuss (the small one), and I also wonder wether a unit test can cover this improvement 🤔

2023-07-06 18:07 UTC, nabokihms commented on connector/oidc/oidc.go
> +	if c.getUserInfo || checkAccessToken {
```suggestion
	if c.getUserInfo {
```
The provider may not have the user info endpoint. Not all providers are entirely OIDC compatible. For these providers, `c.getUserInfo` is a kind of protection.

2023-07-06 18:07 UTC, nabokihms commented on connector/oidc/oidc.go
> +			checkAccessToken = true
```suggestion
```

2023-07-06 18:07 UTC, nabokihms commented on connector/oidc/oidc.go
> +	var checkAccessToken bool
```suggestion
```

2023-07-06 18:24 UTC, seankhliao commented
Not sure which question you were referring to?
I've switched to a check ensuring getUserInfo is enabled.
I can test that getUserInfo needs to be set, not sure we can easily test actual opaque tokens.

2023-07-09 08:30 UTC, nabokihms commented
@seankhliao it was the question about what you have already fixed. Now everything seems fine.

2023-08-01 08:32 UTC, nabokihms approved these changes
LGTM

2023-08-01 08:32 UTC, merged

2025-03-02 22:00 UTC, Moulick commented on connector/oidc/oidc.go
> +			}
Maybe I am mistaking something but this breaks using GitHub Actions (https://token.actions.githubusercontent.com) as an OIDC connector. https://token.actions.githubusercontent.com does not have a userInfo endpoint (https://token.actions.githubusercontent.com/.well-known/openid-configuration). If I set `getUserInfo: false` then this check fails but if `true` then there is no URL to actually do the check!