feat: allow domain names or IDs in keystone connector
dexidp/dex pull request #3506
Opened 2024-05-03 23:37 UTC by cardoe

OpenStack Keystone allows a user to authenticate against a domain. That domain can be specified either as the domain ID or the domain name when authenticating. The domain ID is a UUID or the special "default" domain ID so key off of that when deciding what to submit to the keystone API. Collapsed the code to share the domainKeystone struct by utilizing omitempty to skip unset fields.

2024-05-31 15:08 UTC, nabokihms requested changes
@cardoe thanks, idea looks great. Could you check why tests didn't pass?
```
--- FAIL: TestValidUserLogin (3.44s)
    --- PASS: TestValidUserLogin/test_with_email_address (1.00s)
    --- PASS: TestValidUserLogin/test_without_email_address (0.99s)
    --- FAIL: TestValidUserLogin/test_with_domain_ID (0.51s)
    --- FAIL: TestValidUserLogin/test_with_domain_Name (0.52s)
```

2024-05-31 19:36 UTC, cardoe commented
It's cause the dex project has actual good tests and is testing against a real keystone while I fudged it in the tests and had hand added the data into my local keystone. So 👍 on having a good test environment. I'll clean this up and improve the test coverage. Thanks again for the review.

2024-06-02 21:28 UTC, cardoe commented
I've now tested it with the rocky container used in the tests as well as my local keystone.

2024-06-02 21:28 UTC, cardoe commented
I've also rebased and fixed up for the log changes that happened recently.

2024-06-03 00:56 UTC, nabokihms approved these changes
Looks great. Thanks for your contribution, @cardoe!

2024-06-03 00:56 UTC, merged